name: Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Get files
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: Update yarn
        run: npm i -g yarn@latest

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/pnpm-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install packages
        run: yarn install

      - name: Release Version
        run: yarn release
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
